
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 2000M

  gateway.api:
    image: gatewayapi
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address=http://inventory.api:8080
    deploy:
      resources:
        limits:
          memory: 300M
    depends_on:
      - identity.api
      - customers.api
      - inventory.api
      - suppliers.api
      - company.api
      - employeepayroll.api

  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: Identity/Identity.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDb=Server=sqlserver;Database=IdentityDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  customers.api:
    image: customersapi
    build:
      context: .
      dockerfile: Customers/Customers.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CustomersDb=Server=sqlserver;Database=CustomersDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  inventory.api:
    image: inventoryapi
    build:
      context: .
      dockerfile: Inventory/Inventory.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__InventoryDb=Server=sqlserver;Database=InventoryDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ServiceUrls__CustomerApi=http://customers.api:8080/
      - ServiceUrls__SupplierApi=http://suppliers.api:8080/
      - ServiceUrls__CompanyApi=http://company.api:8080/
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  suppliers.api:
    image: suppliersapi
    build:
      context: .
      dockerfile: Suppliers/Suppliers.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SuppliersDb=Server=sqlserver;Database=SuppliersDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  company.api:
    image: companyapi
    build:
      context: .
      dockerfile: company/Company.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CompanyDb=Server=sqlserver;Database=CompanyDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
    volumes:
      - company-uploads:/app/wwwroot/uploads
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  employeepayroll.api:
    image: employeepayrollapi
    build:
      context: .
      dockerfile: employeepayroll/employeepayroll.api/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EmployeePayrollDb=Server=sqlserver;Database=EmployeePayrollDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  electric-ui:
    image: electricui
    build:
      context: ../../ElectricApps
      dockerfile: Dockerfile.prod
    ports:
      - "4201:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
    depends_on:
      - gateway.api

volumes:
  company-uploads:
  sql-data:
