
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_MEMORY_LIMIT_MB=1500
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  gateway.api:
    image: gatewayapi
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address=http://inventory.api:8080
    deploy:
      resources:
        limits:
          memory: 300M
    depends_on:
      - identity.api
      - customers.api
      - inventory.api
      - suppliers.api
      - company.api

  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: Identity/Identity.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDb=Server=sqlserver;Database=IdentityDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Console
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver

  customers.api:
    image: customersapi
    build:
      context: .
      dockerfile: Customers/Customers.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CustomersDb=Server=sqlserver;Database=CustomersDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - RabbitMQ__Host=rabbitmq
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver
      - rabbitmq

  inventory.api:
    image: inventoryapi
    build:
      context: .
      dockerfile: Inventory/Inventory.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__InventoryDb=Server=sqlserver;Database=InventoryDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ServiceUrls__CustomerApi=http://customers.api:8080/
      - ServiceUrls__SupplierApi=http://suppliers.api:8080/
      - ServiceUrls__CompanyApi=http://company.api:8080/
      - RabbitMQ__Host=rabbitmq
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - company-uploads:/app/wwwroot/uploads
    depends_on:
      - sqlserver
      - rabbitmq

  suppliers.api:
    image: suppliersapi
    build:
      context: .
      dockerfile: Suppliers/Suppliers.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SuppliersDb=Server=sqlserver;Database=SuppliersDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - RabbitMQ__Host=rabbitmq
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver
      - rabbitmq

  company.api:
    image: companyapi
    build:
      context: .
      dockerfile: company/Company.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CompanyDb=Server=sqlserver;Database=CompanyDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__LogsDb=Server=sqlserver;Database=ErrorLogsDb;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
    volumes:
      - company-uploads:/app/wwwroot/uploads
    deploy:
      resources:
        limits:
          memory: 400M
    depends_on:
      - sqlserver


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          memory: 300M

  electric-ui:
    image: electricui
    build:
      context: ../../ElectricApps
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
      - "4201:80"
    volumes:
      - company-uploads:/usr/share/nginx/html/uploads
      - /home/azureuser/certs:/home/azureuser/certs:ro
      - /home/azureuser/app/ElectricApps/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    deploy:
      resources:
        limits:
          memory: 250M
    depends_on:
      - gateway.api

volumes:
  company-uploads:
  sql-data:
  rabbitmq-data:
