public record CreatePurchaseOrderDto(
    Guid SupplierId,
    string SupplierName,
    Guid PriceListId,
    DateTime PoDate,
    DateTime? ExpectedDeliveryDate,
    string Remarks,
    decimal TotalQuantity,
    decimal TotalTax,
    decimal SubTotal,
    decimal GrandTotal,
    string? TaxType,
    decimal? TdsPercent,
    decimal? TcsPercent,
    decimal? TdsAmount,
    decimal? TcsAmount,
    decimal? IgstAmount,
    decimal? CgstAmount,
    decimal? SgstAmount,
    string CreatedBy,
    bool IsQuick, // Quick Purchase flag
    Guid CompanyId,
    string? BranchId,
    List<PoItemDto> Items,
    string? SupplierInvoiceNo = null,
    DateTime? SupplierInvoiceDate = null,
    string? SupplierGstIn = null,
    bool IsRcm = false,
    decimal? RcmGstRate = null,
    decimal? RcmTaxAmount = null,
    decimal? RcmCgstAmount = null,
    decimal? RcmSgstAmount = null,
    decimal? RcmIgstAmount = null,
    bool RcmPaid = false,
    DateTime? RcmPaidDate = null);

public record PoItemDto(
    Guid ProductId,
    decimal Qty,
    string Unit,
    decimal Rate,
    decimal DiscountPercent,
    decimal GstPercent,
    decimal TaxAmount,
    decimal Total,
    DateTime? ManufacturingDate,
    DateTime? ExpiryDate,
    Guid? ProductVariantId = null);
